Bump @babel/eslint-parser from 7.23.10 to 7.24.7 (#549)
* Bump @babel/eslint-parser from 7.23.10 to 7.24.7

Bumps [@babel/eslint-parser](https://github.com/babel/babel/tree/HEAD/eslint/babel-eslint-parser) from 7.23.10 to 7.24.7.
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.24.7/eslint/babel-eslint-parser)

---
updated-dependencies:
- dependency-name: "@babel/eslint-parser"
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* move retry script

* update command

* move command

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Michael D'Angelo <michael.l.dangelo@gmail.com>

diff --git a/.github/workflows/github-pages.yml b/.github/workflows/github-pages.yml
--- a/.github/workflows/github-pages.yml
+++ b/.github/workflows/github-pages.yml
@@ -39,8 +39,29 @@ jobs:
           cache: "npm"
       - name: Install
         run: npm ci
-      - name: Build and render
-        run: npm run predeploy
+      - name: Build and Render
+        shell: bash
+        run: |
+          # NOTE: Rendering can be flaky and react-snap is no
+          # longer maintained, so retry until I convert to next.
+          function retry {
+            local n=1
+            local max=5
+            local delay=1
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                fi
+              }
+            done
+          }
+          retry npm run predeploy
         env:
           NODE_ENV: production
           # Remove this line if you would like to skip using google analytics
