move command

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -53,7 +53,25 @@ jobs:
       - run: npm ci
       - name: Build and Statically Render
         shell: bash
-        run: npm run retry -- npm run predeploy
+        run: |
+          function retry {
+            local n=1
+            local max=5
+            local delay=1
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                fi
+              }
+            done
+          }
+          retry npm run predeploy
         env:
           NODE_ENV: development
       - name: Test
